/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import dao.ManagerApplication;
import Entity.Modele;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import Models.ListModel;
import outils.Messages;
import Tools.Verification;

/**
 *
 * @author ADMIN
 */
public class Fen_Modele extends javax.swing.JFrame {

    private Verification verif;

    /**
     * Creates new form Fen_Modele
     */
    public Fen_Modele() {
        initComponents();
        this.setTitle("Gestion de l'application");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listModel = new javax.swing.JList<>();
        boutCreerModel = new javax.swing.JButton();
        labNom = new javax.swing.JLabel();
        labDiam = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        textDiam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listModel.setModel(new ListModel());
        listModel.setCellRenderer(new rendus.RenduModele());
        listModel.addListSelectionListener(new EcouteListModel());
        jScrollPane1.setViewportView(listModel);

        boutCreerModel.setText("Creer Modele");
        boutCreerModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutCreerModelActionPerformed(evt);
            }
        });

        labNom.setText("     Nom");

        labDiam.setText(" Diametre");

        textNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(boutCreerModel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNom)
                    .addComponent(labNom, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labDiam)
                    .addComponent(textDiam, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labDiam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutCreerModel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutCreerModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutCreerModelActionPerformed
        String diam = textDiam.getText();
        String nom = textNom.getText();
                
        if (!  Verification.estString(nom))  
        {        
            Messages.warning (this, "Nom modèle incorrect");
            textNom.setText("");
        }
        else  if (! Verification.estNumeric(diam) )
            Messages.warning (this, "Diamètre incorrect");
        else
        {
            float diametre = Float.parseFloat(diam);
            if (ManagerApplication.creerModele(nom, diametre)) 
            {
                Messages.info (this, ManagerApplication.getMessage());
                ManagerApplication.listModel();
                System.out.println("ok");
                ListModel m = (ListModel) listModel.getModel();
                m.refresh();
            } 
            else
            {
                Messages.erreur (this, ManagerApplication.getMessage());                                                 ;
            }

            textNom.setText("");
            textDiam.setText("");
        }
    }//GEN-LAST:event_boutCreerModelActionPerformed
    
    
    private void textNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomActionPerformed

    private class EcouteListModel implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            int index = e.getFirstIndex();
            Modele m = listModel.getSelectedValue();

            // on change la valeur du diametre en String
            // pour pouvoir l'afficher dans le textDiam.
            String diam = String.valueOf(m.getDiametre());

            textDiam.setText(diam);
            textNom.setText(m.getNom());
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutCreerModel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labDiam;
    private javax.swing.JLabel labNom;
    private javax.swing.JList<Modele> listModel;
    private javax.swing.JTextField textDiam;
    private javax.swing.JTextField textNom;
    // End of variables declaration//GEN-END:variables
}
