package Views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ramba
 */
public class Identification extends javax.swing.JFrame {

    /**
     * Creates new form Identification
     */
    public Identification() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitreIdentification = new javax.swing.JLabel();
        lbUtilisateur = new javax.swing.JLabel();
        labelPrenomIdentification = new javax.swing.JLabel();
        tfUtilisateur = new javax.swing.JFormattedTextField();
        butConnexion = new javax.swing.JButton();
        lbImageIdentification = new javax.swing.JLabel();
        passIdentification = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 600, 600));

        lbTitreIdentification.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitreIdentification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitreIdentification.setText("Bretagne Ouest Unités Moteur ");

        lbUtilisateur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbUtilisateur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbUtilisateur.setText("Utilisateur");

        labelPrenomIdentification.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPrenomIdentification.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPrenomIdentification.setText("Mot de passe");

        tfUtilisateur.setToolTipText("");

        butConnexion.setText("Connexion");
        butConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConnexionActionPerformed(evt);
            }
        });

        lbImageIdentification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/auto_repair.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPrenomIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(butConnexion)
                    .addComponent(tfUtilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(passIdentification))
                .addGap(18, 18, 18)
                .addComponent(lbImageIdentification, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE))
            .addComponent(lbTitreIdentification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitreIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUtilisateur))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPrenomIdentification)
                            .addComponent(passIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(butConnexion))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImageIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConnexionActionPerformed
        // TODO add your handling code here:
        new Responsable_Application_Machines().setVisible(true);
        System.out.println("Program launched");
    }//GEN-LAST:event_butConnexionActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butConnexion;
    private javax.swing.JLabel labelPrenomIdentification;
    private javax.swing.JLabel lbImageIdentification;
    private javax.swing.JLabel lbTitreIdentification;
    private javax.swing.JLabel lbUtilisateur;
    private javax.swing.JPasswordField passIdentification;
    private javax.swing.JFormattedTextField tfUtilisateur;
    // End of variables declaration//GEN-END:variables
}
