/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author ramba
 */
public class Responsable_Application_Seuils extends javax.swing.JFrame {

    /**
     * Creates new form Responsable_Application_Seuils
     */
    public Responsable_Application_Seuils() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitreManageur = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabManageurSeuils = new javax.swing.JTable();
        butModifierSeuil = new javax.swing.JButton();
        lbSeuil = new javax.swing.JLabel();
        tfManageurSeuil = new javax.swing.JFormattedTextField();
        butDeconnexion = new java.awt.Button();
        menuApplication = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        menuModeles = new javax.swing.JMenu();
        menuMachines = new javax.swing.JMenu();
        menuSeuils = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labTitreManageur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitreManageur.setText("Manageur production");

        tabManageurSeuils.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Modèles", "Catégories", "Seuils"
            }
        ));
        jScrollPane1.setViewportView(tabManageurSeuils);

        butModifierSeuil.setText("Modifier");

        lbSeuil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSeuil.setText("Seuil");

        butDeconnexion.setBackground(new java.awt.Color(255, 153, 0));
        butDeconnexion.setLabel("Déconnexion");
        butDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeconnexionActionPerformed(evt);
            }
        });

        menuFichier.setText("Fichier");
        menuApplication.add(menuFichier);

        menuModeles.setText("Modèles");
        menuApplication.add(menuModeles);

        menuMachines.setText("Machines");
        menuApplication.add(menuMachines);

        menuSeuils.setText("Seuils");
        menuApplication.add(menuSeuils);

        setJMenuBar(menuApplication);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(labTitreManageur, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(lbSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(tfManageurSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(butModifierSeuil)))
                .addContainerGap(368, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(butDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitreManageur, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSeuil)
                    .addComponent(tfManageurSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butModifierSeuil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(butDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeconnexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butDeconnexionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button butDeconnexion;
    private javax.swing.JButton butModifierSeuil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labTitreManageur;
    private javax.swing.JLabel lbSeuil;
    private javax.swing.JMenuBar menuApplication;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JMenu menuMachines;
    private javax.swing.JMenu menuModeles;
    private javax.swing.JMenu menuSeuils;
    private javax.swing.JTable tabManageurSeuils;
    private javax.swing.JFormattedTextField tfManageurSeuil;
    // End of variables declaration//GEN-END:variables
}
